version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_INTERNAL://kafka-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  product-service:
    build: ./product-service
    image: product-service:latest
    container_name: product-service
    ports:
      - "8083:8080" # Map container's 8080 to host's 8083
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kafka # ensures kafka starts before dependent services

  customer-service:
    build: ./customer-service
    ports:
      - "8082:8080" # map container's 8080 to host's 8082
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kafka

  order-service:
    build: ./order-service
    ports:
      - "8083:8080" 
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kafka

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8080" 
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kafka

  postgres:
    image: 'postgres:15'
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservices-with-kafka
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:











#version: '3'
#services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  bookpublisher:
    build: ./book-publisher
    container_name: bookpublisher
    depends_on:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: 'production'
      DEVTIRO_KAFKA_TOPIC: 'books.published'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  bookpersistence:
    build: ./book-persistence
    container_name: bookpersistence
    depends_on:
      - broker
    ports:
      - "8181:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'production'
      DEVTIRO_KAFKA_NOTIFICATION_TOPIC: 'notification.created'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  authorpersistence:
    build: ./author-persistence
    container_name: authorpersistence
    depends_on:
      - broker
    ports:
      - "8282:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'production'
      DEVTIRO_KAFKA_NOTIFICATION_TOPIC: 'notification.created'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

  notifications:
    build: ./notifications
    container_name: notifications
    depends_on:
      - broker
    ports:
      - "8383:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'production'
      DEVTIRO_KAFKA_TOPIC: 'notification.created'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'